### ISSUE TITLE
rsem error

### ISSUE THREAD

**Issue by prefectus** [YosefLab/TRAPeS#5]
Dear Shaked,
I get following error while running TRAPeS on our data:

2018-01-20 18:49:17.504397 Working on: test
2018-01-20 18:49:17.508777 Pre-processing alpha chain
2018-01-20 18:49:17.527181 Bases parameter is bigger than the length of the J segment, appending the C segment to the J segment
2018-01-20 18:49:23.235297 Pre-processing beta chain
2018-01-20 18:49:23.333654 Did not find any V-J reads, searching for V-C and J-C reads:
2018-01-20 18:49:24.178754 Bases parameter is bigger than the length of the V or J segment, taking the lengthof the V/J segment instead, which is: 46
2018-01-20 18:49:24.179485 Bases parameter is bigger than the length of the V or J segment, taking the lengthof the V/J segment instead, which is: 49
2018-01-20 18:49:31.243698 Reconstructing beta chains
2018-01-20 18:50:09.346195 Reconstructing alpha chains
2018-01-20 18:51:36.491648 Creating full TCR sequencing
2018-01-20 18:51:36.571641 Running RSEM to quantify expression of all possible isoforms
Traceback (most recent call last):
  File "./trapes.py", line 1868, in <module>
    args.oneSide)
  File "./trapes.py", line 66, in runTCRpipe
    minOverlap, rsem, bowtie2, lowQ, samtools, top, byExp, readOverlap, oneSide)
  File "./trapes.py", line 254, in runSingleCell
    runRsem(outDir, rsem, bowtie2, fullTcrFileAlpha, fullTcrFileBeta, output, samtools)
  File "./trapes.py", line 1115, in runRsem
    '-q', fullTcrFileAlpha, rsemIndDir + '/VDJ.alpha.seq'])
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

The command line: 
./trapes.py -genome hg38 -oneSide -sumF test -path /path -strand none -output test -bam TopHat_Output/accepted_hits.bam -unmapped TopHat_Output/unmapped.bam -score 80 -bases 150 -top 15 -byExp 

Thank you very much,
Till

**Comment by shakea02** [comment]
Dear Till,

The error comes from TRAPeS not being able to run RSEM. Is rsem in your default path? If not, you need to specify the RSEM path with the parameter -rsem.
Let me know if that helps or if you have anymore problems.

Best,
Shaked.
