### ISSUE TITLE
DeprecationWarning: 'U' mode is deprecated

### ISSUE THREAD

**Issue by bk11-lab** [YosefLab/TRAPeS#8]
Dear Shaked,
I got the following error while trying to run TRAPeS on my data. 
2020-05-29 22:22:53.066237 Working on: PB_629_L001-hisat2-sorted
/usr/local/analysis/trapes/20191013-20ea562/bin/trapes.py:1809: DeprecationWarning: 'U' mode is deprecated
  inF = open(fasta,'rU')
2020-05-29 22:22:53.088833 Pre-processing alpha chain
Traceback (most recent call last):
  File "/usr/local/analysis/trapes/20191013-20ea562/bin/trapes.py", line 1896, in <module>
    args.oneSide, args.Aminus, args.Bminus)
  File "/usr/local/analysis/trapes/20191013-20ea562/bin/trapes.py", line 48, in runTCRpipe
    minOverlap, rsem, bowtie2, lowQ, samtools, top, byExp, readOverlap, oneSide, Aminus, Bminus, genome)
  File "/usr/local/analysis/trapes/20191013-20ea562/bin/trapes.py", line 239, in runSingleCell
    unDictAlpha = analyzeChain(fastaDict, vdjDict, output, bam, unmapped, idNameDict, bases, 'A', strand, lowQ, top, byExp, readOverlap, Aminus, Bminus, organism)
  File "/usr/local/analysis/trapes/20191013-20ea562/bin/trapes.py", line 1303, in analyzeChain
    junctionSegs = makeJunctionFile(bam, chain, output, bases, vdjDict, fastaDict, idNameDict, top, byExp, readOverlap)
  File "/usr/local/analysis/trapes/20191013-20ea562/bin/trapes.py", line 1335, in makeJunctionFile
    (vjReads, vjCounts) = loadReadsToDict(vjSegs, mappedFile, vjReads, readOverlap)
  File "/usr/local/analysis/trapes/20191013-20ea562/bin/trapes.py", line 1413, in loadReadsToDict
    readsIter = mappedFile.fetch(chr, start-1, end+1)
  File "pysam/libcalignmentfile.pyx", line 1081, in pysam.libcalignmentfile.AlignmentFile.fetch
  File "pysam/libchtslib.pyx", line 687, in pysam.libchtslib.HTSFile.parse_region
ValueError: invalid contig `chr14`

The command line:
`trapes.py -genome hg19 -path Fluidigm_C1_singleCell/test/foo/ -sumF Fluidigm_C1_singleCell/test/foo/TRAPeS_out/TCR.out -output Fluidigm_C1_singleCell/test/foo/TRAPeS_out/TCR.out -score 15 -unmapped genome.unmapped.bam -bam genome.bam`

Thank you!
bk

**Comment by shakea02** [comment]
Hello,
Thank you for your interest in TRAPeS! 
The Deprecation Warning is just a warning and TRAPeS should run even with it. 
The problem you get is because of different chromosomes naming between TRAPeS' data files and your bam file. For hg19, TRAPeS expects the bam file to have chromosomes named as "chr1, chr2, etc...".  
To fix it you can do one of two things:
1. Rerun your alignments to the hg19 genome with the appropriate naming
2. In the Data/hg19 folder, manually change the chromosome names in hg19.TCR.bed to have the same names as in your bam file.

Let me know if you have any other questions!
Best,
Shaked

**Comment by bk11-lab** [comment]
Hi,
It was a great help that I was able to overcome that issue. However, I have again come across the another issue with the following error message.
2020-06-01 01:59:30.654558 Working on: PB_629_L001-hisat2-sorted
/usr/local/analysis/trapes/20191013-20ea562/bin/trapes.py:1809: DeprecationWarning: 'U' mode is deprecated
  inF = open(fasta,'rU')
2020-06-01 01:59:30.675165 Pre-processing alpha chain
2020-06-01 01:59:30.686815 Did not find any V-J reads, searching for V-C and J-C reads:
2020-06-01 01:59:40.985494 Pre-processing beta chain
2020-06-01 01:59:41.058580 Did not find any V-J reads, searching for V-C and J-C reads:
Traceback (most recent call last):
  File "/usr/local/analysis/trapes/20191013-20ea562/bin/trapes.py", line 1896, in <module>
    args.oneSide, args.Aminus, args.Bminus)
  File "/usr/local/analysis/trapes/20191013-20ea562/bin/trapes.py", line 48, in runTCRpipe
    minOverlap, rsem, bowtie2, lowQ, samtools, top, byExp, readOverlap, oneSide, Aminus, Bminus, genome)
  File "/usr/local/analysis/trapes/20191013-20ea562/bin/trapes.py", line 242, in runSingleCell
    unDictBeta = analyzeChain(fastaDict, vdjDict, output, bam, unmapped, idNameDict, bases, 'B', strand, lowQ, top, byExp, readOverlap, Aminus, Bminus, organism)
  File "/usr/local/analysis/trapes/20191013-20ea562/bin/trapes.py", line 1303, in analyzeChain
    junctionSegs = makeJunctionFile(bam, chain, output, bases, vdjDict, fastaDict, idNameDict, top, byExp, readOverlap)
  File "/usr/local/analysis/trapes/20191013-20ea562/bin/trapes.py", line 1341, in makeJunctionFile
    (cReads, cCountsDict) = loadReadsToDict(vdjChainDict['C'], mappedFile, cReads, readOverlap)
  File "/usr/local/analysis/trapes/20191013-20ea562/bin/trapes.py", line 1419, in loadReadsToDict
    if overlap >= readOverlap:
TypeError: '>=' not supported between instances of 'NoneType' and 'int'

Would you please help me where the problem lies?

My command line is:
`trapes.py -genome hg19 -path Fluidigm_C1_singleCell/test/foo/ -sumF Fluidigm_C1_singleCell/test/foo/TRAPeS_out/TCR.out -output Fluidigm_C1_singleCell/test/foo/TRAPeS_out/TCR.out -score 15 -unmapped genome.unmapped.bam -bam genome.bam`

Thank you!
BK

**Comment by shakea02** [comment]
Hey,
From what I can see, there is a problem in the get_overlap commend from the pysam package when reading your bam file. I've encountered it before when inputting bam files created by hisat2. I still haven't figured out what the problem is, but in the meantime I can suggest using a different aligner such as tophat2 or STAR.

Thanks,
Shaked

**Comment by bk11-lab** [comment]
Hi Shaked,
I used the STAR for the alignment and it worked fine. 

I am seeing this in the log file:
2020-06-02 15:04:11.212043 Working on: PA_320_L001-STAR
2020-06-02 15:04:11.218870 Pre-processing alpha chain
2020-06-02 15:04:30.409517 Pre-processing beta chain
2020-06-02 15:04:46.776177 Reconstructing beta chains
2020-06-02 15:04:48.986601 Reconstructing alpha chains
2020-06-02 16:41:21.777149 Creating full TCR sequencing
2020-06-02 16:41:21.781169 Running RSEM to quantify expression of all possible isoforms
*2020-06-02 16:41:21.784052 Did not reconstruct any alpha chains, not running RSEM on alpha
*2020-06-02 16:41:21.784320 Did not reconstruct any beta chains, not running RSEM on beta
2020-06-02 16:41:21.784393 Finding productive CDR3
2020-06-02 16:41:21.788882 Writing results to summary file
Is there any thing wrong with this? The RSEM did not quantify the expressions and the summary file is empty with only header info. 
`Chain	Status	Rank of TCR	V	J	C	CDR3 NT	CDR3 AA	#reads in TCR	#reads in CDR3	#reads in V	#reads in J	#reads in C	%unmapped reads used in the reconstruction	# unmapped reads used in the reconstruction	%unmapped reads in CDR3	#unmapped reads in CDR3	V ID	J ID	C ID`
The command used 
`trapes.py \
	-genome hg19 \
	-path /Fluidigm_C1_singleCell/STAR_Alignment/STAR_Alignment_RE/TRAPeS_RE/ \
	-sumF TRAPeS_results/TCR.out \
	-output TRAPeS_results/TCR.out \
	-score 15 \
	-lowQ \
	-unmapped genome.unmapped.bam \
	-bam genome.mapped.bam`

**Comment by shakea02** [comment]
Hi,
This output means that there were no successful results for the bam file you gave. This could be for several reasons, but I would guess that there were no genomic alignment to V/J segments so TRAPeS couldn't start the reconstruction. There should be a file named *.summary.txt, what does it say? If it says "didn't find any genomic alignment to V/J segments" than this indeed could be the problem.
If that's the case, I would suggest going over the STAR parameters to make sure you are aligning also to the genome and not only to the transcriptome. Also I would make sure that the alignment is for hg19 and not hg38 (happened to me more than once :) ).

Best,
Shaked

**Comment by bk11-lab** [comment]
Hi,
*.summary.txt file looks like this:
sample  alpha   beta
PA_001_L001-STAR        Failed - didn't find any V and J segments in original mapping   Failed - didn't find any V and J segments in original mapping
PA_002_L001-STAR        Failed - didn't find any V and J segments in original mapping   Failed - didn't find any V and J segments in original mapping
PA_004_L001-STAR        Failed - didn't find any V and J segments in original mapping   Failed - didn't find any V and J segments in original mapping

I am using the same reference builds for STAR and TRAPeS. My parameters for STAR are:
`STAR \
        --genomeDir ${STAR_INDEX} \
        --readFilesIn ${new_r1}-paired-trim.fastq ${new_r2}-paired-trim.fastq \
        --runThreadN ${SLURM_CPUS_ON_NODE} \
        --outSAMtype BAM SortedByCoordinate \
        --quantMode TranscriptomeSAM GeneCounts \
        --outSAMunmapped Within \
        --sjdbGTFfile ${gtf} \
        --outFileNamePrefix "${bam_name}"`
Will you please suggest me about the parameters that I should use for STAR alignment?
I really appreciate your help.
Thanks you!

BK

**Comment by shakea02** [comment]
Hi,
Sorry for the late reply, I’m traveling for the next few days. I can look
into it more in a few days, but in the meantime I can recommend trying
genome hg38 instead of hg19. It has better annotations regarding the TCR
segments.
